/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.xml.ws.Endpoint;

public class App {
    public static void main(String[] args) {
        String url = "http://localhost:8085/TemperatureService";
        Endpoint.publish(url, new TemperatureService());
        System.out.println("Service published at: " + url);
    }
}
